#!/bin/bash

_set-device() {
    local cur=${COMP_WORDS[COMP_CWORD]}
    if [ $COMP_CWORD -eq 1 ]; then
        local functions=$(grep -oP '^[^_]\w+\s*\(\)' /usr/bin/set-device | sed 's/()//')
        COMPREPLY=($(compgen -W "$functions" -- $cur))
    elif [ $COMP_CWORD -eq 2 ]; then
        local prefix=$(grep "^overlay_prefix=" /boot/config.txt | cut -d'=' -f2)
        local dtbo=()
        for file in /boot/overlays/"$prefix"-*.dtbo; do
            dtbo+=($(basename "$file" .dtbo | sed "s/^$prefix-//"))
        done
        COMPREPLY=($(compgen -W "${dtbo[*]}" -- $cur))
    fi
}
complete -F _set-device set-device

