#!/bin/bash


prefix=$(grep "^overlay_prefix=" /boot/config.txt | cut -d'=' -f2)
# echo $prefix
dtbo=()
for file in /boot/overlays/"$prefix"-*.dtbo; do
    dtbo+=($(basename "$file" .dtbo | sed "s/^$prefix-//"))
done




_is_in_dtbo() {
    name=$1
    if [[ " ${dtbo[*]} " == *" $1 "* ]]; then
        return 1
    else
        return 0
    fi
}

_is_in_overlays() {
    name=$1
    overlays=$(grep "^overlays=" /boot/config.txt | cut -d'=' -f2)

    if [[ $overlays =~ (^|[[:space:]])"$1"($|[[:space:]]) ]]; then
        return 1
    else
        return 0
    fi

}

status() {
    if [ ! -z "$1" ]; then
        _is_in_dtbo $1
        if [ $? -eq 1 ]; then
            dtbo=("$1")
        else
            exit 1
        fi

    fi

    echo -e "\n-------------------------"
    overlays=$(grep "^overlays=" /boot/config.txt | cut -d'=' -f2)
    for d in "${dtbo[@]}"; do
        len=${#d}
        tabs=$((15-len))

        _is_in_overlays $d
        if [ $? -eq 1 ]; then
            echo -en "\033[32m"
        else
            echo -en "\033[31m"
        fi
    
        echo -en "  $d"
        for ((i = 0; i < tabs; i++)); do
            echo -ne "="
        done

        _is_in_overlays $d
        if [ $? -eq 1 ]; then
            echo -e "|enable|"
        else
            echo -e "| off  |"
        fi
        echo -en "\033[0m"
    done
    echo -e "-------------------------\n"
}

enable() {
    if [ ! -z "$1" ]; then
        _is_in_dtbo $1
        if [ ! $? -eq 1 ]; then
            echo "device name error"
            exit 1
        fi
    else
        echo "please choose device"
        exit -1
    fi

    _is_in_overlays $1
    if [ ! $? -eq 1 ]; then
        echo -e "enable: $1"
        sed -i "/^overlays=/ s/$/ $1/" /boot/config.txt

    fi
    
}

disable() {
    if [ ! -z "$1" ]; then
        _is_in_dtbo $1
        if [ ! $? -eq 1 ]; then
            echo "device name error"
            exit 1
        fi
    else
        echo "please choose device"
        exit -1
    fi

    _is_in_overlays $1
    if [  $? -eq 1 ]; then
        echo -e "disable: $1"
        sed -i "/^overlays=/ s/\b$1\b//g" /boot/config.txt

    fi
}


FUNCTION_NAME=$1
DTB_NAME=$2
$FUNCTION_NAME $DTB_NAME