#!/bin/bash
BOARD_NAME="k230"
BOARD_MODEL="k230"
CHIP_ARCH="riscv64"

# 使用指定下载的gcc
TOOLCHAIN_DOWN_URL="https://occ-oss-prod.oss-cn-hangzhou.aliyuncs.com/resource//1721095219235/Xuantie-900-gcc-linux-6.6.0-glibc-x86_64-V2.10.1-20240712.tar.gz"
TOOLCHAIN_FILE_NAME="Xuantie-900-gcc-linux-6.6.0-glibc-x86_64-V2.10.1"
CROSS_COMPILE="riscv64-unknown-linux-gnu-"

# 使用本机自带的gcc，不存在则现场apt安装
# TOOLCHAIN_NAME_IN_APT="gcc-aarch64-linux-gnu"
# CROSS_COMPILE="aarch64-linux-gnu-"

BOOTLOADER_NAME="u-boot"

# SYTERKIT_GIT="https://github.com/walnutpi/SyterKit.git"
# SYTERKIT_BRANCH="main"
# SYTERKIT_BOARD_FILE="walnutpi-2b.cmake"
# SYTERKIT_OUT_BIN="board/walnutpi-2b/extlinux_boot/extlinux_boot_bin_card.bin"


# ATF_GIT="https://github.com/ARM-software/arm-trusted-firmware.git"
# ATF_PLAT="sun50i_h616"
# ATF_BRANCH="lts-v2.10.2"

UBOOT_GIT="https://github.com/sc-bin/u-boot.git"
UBOOT_BRANCH="v2022.10-k230"
UBOOT_CONFIG="k230_canmv_01studio_defconfig"
# UBOOT_BIN_NAME="u-boot.bin"
UBOOT_BIN_NAME_2M="fn_u-boot.img"
UBOOT_BIN_NAME_1M="u-boot-spl-k230.bin"

LINUX_GIT="https://github.com/sc-bin/linux-xuantie-kernel.git"
LINUX_BRANCH="linux-6.6.36"
LINUX_CONFIG="k230_defconfig"
MODULES_ENABLE="8189fs "
FIRMWARE_GIT="https://github.com/walnutpi/firmware.git"

BR2_PACKAGE_RTL8189FS=y
BR2_PACKAGE_VVACM_DRIVER=y

