# DO NOT EDIT THIS FILE



if test -z "${save_flag}"; then
    setenv bootdelay 3

    setenv fdt_addr_r 0x2200000

    setenv load_addr 0xa000000
    setenv dtb_addr 0xa000000
    setenv fdt_high 0xa100000
    setenv fdtcontroladdr 80293880

    setenv gatewayip 10.99.105.254
    setenv ipaddr 10.99.105.44
    setenv kernel_addr 0xc100000
    setenv loadaddr 0xc000000
    setenv netmask 255.255.255.0
    setenv ramdisk_addr 0xa100000
    setenv serverip 10.10.1.94
    setenv vendor canaan
    setenv quick_boot false
    setenv k Image
    setenv kilp32 Image_ilp32
    setenv nuttex nuttx-7000000-uart2.bin
	setenv save_flag 1
    saveenv
fi
if test -e mmc ${mmc_boot_dev_num} config.txt; then
	load mmc ${mmc_boot_dev_num} ${load_addr} config.txt
	env import -t ${load_addr} ${filesize}
fi

if test "${display_bootinfo}" = "enable"; then setenv consoleargs_diplay "console=tty0"; fi

if test "${console_uart}" = "uart0"; then setenv consoleargs "console=ttyS0,115200"; fi
if test "${console_uart}" = "uart1"; then setenv consoleargs "console=ttyS1,115200"; fi
if test "${console_uart}" = "uart2"; then setenv consoleargs "console=ttyS2,115200"; fi
if test "${console_uart}" = "uart3"; then setenv consoleargs "console=ttyS3,115200"; fi
if test "${console_uart}" = "uart4"; then setenv consoleargs "console=ttyS4,115200"; fi
if test "${console_uart}" = "null"; then setenv consoleargs "console=/dev/null"; fi

if test "${bootlogo}" = "true"; then
	setenv consoleargs "splash plymouth.ignore-serial-consoles ${consoleargs}"
else
	setenv consoleargs "splash=verbose ${consoleargs}"
fi
setenv args_console "${consoleargs} ${consoleargs_diplay}"
setenv bootargs "root=${rootdev} rootwait rw rootfstype=${rootfstype} net.ifnames=0 ${args_console} consoleblank=0 loglevel=${printk_level} usb-storage.quirks=${usbstoragequirks} ${extraargs}"

# 加载设备树
if mmc dev 1; then
	echo "board has emmc"
	mmc dev 0
	load mmc ${mmc_boot_dev_num}:1 ${fdt_addr_r} ${fdtfile_emmc}.dtb
else
	echo "board not emmc"
	load mmc ${mmc_boot_dev_num}:1 ${fdt_addr_r} ${fdtfile}.dtb
fi

# 启动nuttex
# fatload mmc ${mmc_boot_dev_num}:1 0x7000000 /${nuttex} && boot_baremetal 0 0x${fileaddr} 0x${filesize};

# 启动linux
fatload mmc ${mmc_boot_dev_num}:1 0x3000000 /fw_jump_add_uboot_head.bin
fatload mmc ${mmc_boot_dev_num}:1 0x200000 /${k}
bootm 0x3000000 - ${fdt_addr_r};

# Recompile with:
# mkimage -C none -A riscv -T script -d boot.cmd boot.scr
