# DO NOT EDIT THIS FILE

setenv bootdelay 3

setenv bootcmd_baremetal 'mmc dev ${mmc_boot_dev_num}; mmc read 0 0x5000 0xa000; boot_baremetal 1 0 1400000;'
setenv bootcmd_usb 'run usb_load; bootm $kernel_addr - $dtb_addr'


setenv dtb_addr 0xa000000
setenv fdt_high 0xa100000
setenv fdtcontroladdr 80293880

setenv gatewayip 10.99.105.254
setenv ipaddr 10.99.105.44
setenv kernel_addr 0xc100000
setenv loadaddr 0xc000000
setenv netmask 255.255.255.0
setenv ramdisk_addr 0xa100000
setenv serverip 10.10.1.94
setenv vendor canaan
setenv quick_boot false
setenv k Image
setenv kilp32 Image_ilp32
setenv nuttex nuttx-7000000-uart2.bin

# 启动nuttex
# fatload mmc ${mmc_boot_dev_num}:1 0x7000000 /${nuttex} && boot_baremetal 0 0x${fileaddr} 0x${filesize};

# 启动linux
fatload mmc ${mmc_boot_dev_num}:1 0x3000000 /fw_jump_add_uboot_head.bin
fatload mmc ${mmc_boot_dev_num}:1 0x200000 /${k}
fatload mmc ${mmc_boot_dev_num}:1 0x2200000 /k230-canmv-01studio.dtb
bootm 0x3000000 - 0x2200000;

# Recompile with:
# mkimage -C none -A riscv -T script -d boot.cmd boot.scr
