#!/bin/bash

_set-vnc () {
    local cur=${COMP_WORDS[COMP_CWORD]}
    if [ $COMP_CWORD -eq 1 ]; then
        local functions=$(grep -oP '^[^_]\w+\s*\(\)' /usr/bin/set-vnc | sed 's/()//')
        COMPREPLY=($(compgen -W "$functions" -- $cur))
    fi
}
complete -F _set-vnc set-vnc


